apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-pipeline-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-pipeline-project
  template:
    metadata:
      labels:
        app: ci-cd-pipeline-project
    spec:
      containers:
      - name: ci-cd-pipeline-project
        image: srujanzz/ci-cd-pipeline-project:test
        ports:
        - containerPort: 8080

