apiVersion: v1
kind: Service
metadata:
  name: ci-cd-pipeline-project-service
spec:
  selector:
    app: ci-cd-pipeline-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

